name: Deploy Backend to VPS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}


      - name: Copy backend files to VPS
        run: |
          rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" backend/ ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/root/score-leaderboard-app

      - name: Set environment variables on VPS
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} "echo 'DATABASE_URL=${{ secrets.DATABASE_URL }}' > /root/score-leaderboard-app/.env"

      - name: Install dependencies and restart backend
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} << 'EOF'
            cd /root/score-leaderboard-app
            npm install
            npm run build
            pm2 restart gdg-qassim-leaderboard-backend || pm2 start dist/index.js --name gdg-qassim-leaderboard-backend
          EOF
